#!/usr/bin/env bash
set -euo pipefail

# Refresh the vendored 45drives-disks frontend snapshot from an upstream
# 45Drives Cockpit module build, then re-apply the Unraid-specific index.html
# shim (routes Cockpit API calls to php/api.php).
#
# The 45drives-disks UI is built and maintained by 45Drives; we only vendor
# their prebuilt output. This script does NOT build from source. It takes an
# already-built upstream module, from one of:
#
#   --release <tag|latest>  Download a build straight from the 45Drives GitHub
#                           releases (45Drives/cockpit-hardware) -- the .deb is
#                           fetched and the 45drives-disks module extracted.
#   --source <dir|tarball>  A directory (e.g. /usr/share/cockpit/45drives-disks
#                           on an installed host) or a tarball of one.
#
# index.html is regenerated by transforming upstream's own index.html: the
# Cockpit-internal `<script src="../...">` tags (which 404 outside Cockpit) are
# stripped and the Unraid shim (dev/45drives-disks-cockpit-shim.html) is
# injected. Upstream's own bundle/asset references (including p5.min.js) are
# preserved as-is, so this survives upstream hash-scheme and bundling changes.

UPSTREAM_REPO="45Drives/cockpit-hardware"

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
DEST_DIR="${ROOT_DIR}/assets/45d/45drives-disks"
SHIM="${ROOT_DIR}/dev/45drives-disks-cockpit-shim.html"
ASSETS_README="${ROOT_DIR}/assets/45d/README.md"

usage() {
  cat <<'EOF'
Update the vendored 45drives-disks frontend snapshot.

Usage:
  dev/update-45drives-disks.sh --release <tag|latest> [--version <ver>] [--dry-run]
  dev/update-45drives-disks.sh --source <dir|tarball>  [--version <ver>] [--dry-run]
  dev/update-45drives-disks.sh <dir|tarball>           [--version <ver>] [--dry-run]

Sources:
  --release <tag|latest>  Pull a build from 45Drives/cockpit-hardware GitHub
                          releases (downloads the .deb, extracts the module).
                          Requires the `gh` CLI (authenticated) and `ar`.
                          Note: releases before ~v2.6 ship no built artifacts.
  --source <src>          An upstream module directory (index.html + assets/),
                          e.g. /usr/share/cockpit/45drives-disks, or a tarball
                          (.txz, .tar.xz, .tgz, .tar.gz, .tar) of one.

Options:
  --version <ver>   Record this release in assets/45d/README.md (e.g. 2.8.2-1).
                    With --release, defaults to the release tag.
  --dry-run         Show what would change without modifying the repo.
  -h, --help        Show this help.

After updating, the committed bundle changes and may differ substantially from
the previous snapshot (45Drives restructures the module across versions). Real-
device visual QA on Unraid Main is required before shipping.
EOF
}

SOURCE=""
RELEASE=""
VERSION=""
DRY_RUN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --release) RELEASE="${2:-}"; shift 2 ;;
    --source)  SOURCE="${2:-}"; shift 2 ;;
    --version) VERSION="${2:-}"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "error: unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)
      if [[ -z "$SOURCE" ]]; then SOURCE="$1"; shift
      else echo "error: unexpected argument: $1" >&2; usage >&2; exit 2; fi ;;
  esac
done

if [[ -n "$RELEASE" && -n "$SOURCE" ]]; then
  echo "error: use either --release or a source, not both" >&2; exit 2
fi
if [[ -z "$RELEASE" && -z "$SOURCE" ]]; then
  echo "error: a --release tag or a source directory/tarball is required" >&2; usage >&2; exit 2
fi
[[ -f "$SHIM" ]] || { echo "error: shim snippet missing: $SHIM" >&2; exit 1; }
[[ -d "$DEST_DIR" ]] || { echo "error: destination missing: $DEST_DIR" >&2; exit 1; }
command -v rsync >/dev/null 2>&1 || { echo "error: rsync is required" >&2; exit 1; }

WORK_DIR=$(mktemp -d)
cleanup() { rm -rf "$WORK_DIR"; }
trap cleanup EXIT

# --- Pull a build from a GitHub release (downloads .deb, extracts module) ----
fetch_release() {
  local rel="$1"
  command -v gh >/dev/null 2>&1 || { echo "error: the gh CLI is required for --release" >&2; return 1; }
  command -v ar >/dev/null 2>&1 || { echo "error: 'ar' is required to unpack the .deb" >&2; return 1; }

  local view_args=(-R "$UPSTREAM_REPO" --json tagName,assets)
  [[ "$rel" != "latest" ]] && view_args+=("$rel")
  local meta tag asset
  meta=$(gh release view "${view_args[@]}" 2>/dev/null) \
    || { echo "error: could not read release '$rel' from $UPSTREAM_REPO" >&2; return 1; }
  tag=$(printf '%s' "$meta" | sed -n 's/.*"tagName":"\([^"]*\)".*/\1/p')

  # Prefer an amd64 .deb (frontend is arch-independent); else any .deb.
  asset=$(printf '%s' "$meta" | grep -oE '"name":"[^"]*amd64\.deb"' | head -n1 | sed 's/.*"name":"\([^"]*\)".*/\1/')
  [[ -z "$asset" ]] && asset=$(printf '%s' "$meta" | grep -oE '"name":"[^"]*\.deb"' | head -n1 | sed 's/.*"name":"\([^"]*\)".*/\1/')
  [[ -n "$asset" ]] || { echo "error: release $tag has no .deb asset (releases before ~v2.6 ship none)" >&2; return 1; }

  local dl="${WORK_DIR}/dl"; mkdir -p "$dl"
  echo "Downloading ${asset} from $UPSTREAM_REPO@${tag}…" >&2
  gh release download ${rel:+$( [[ "$rel" != latest ]] && printf '%s' "$rel" )} \
     -R "$UPSTREAM_REPO" -p "$asset" -D "$dl" >&2 \
    || { echo "error: download failed" >&2; return 1; }

  local deb; deb=$(ls "$dl"/*.deb 2>/dev/null | head -n1)
  [[ -n "$deb" ]] || { echo "error: no .deb downloaded" >&2; return 1; }

  local ex="${WORK_DIR}/deb"; mkdir -p "$ex"
  ( cd "$ex" && ar x "$deb" )
  local data; data=$(ls "$ex"/data.tar.* 2>/dev/null | head -n1)
  [[ -n "$data" ]] || { echo "error: .deb has no data tarball" >&2; return 1; }

  local mod="${WORK_DIR}/release-module"; mkdir -p "$mod"
  local member="./usr/share/cockpit/45drives-disks"
  case "$data" in
    *.xz)  tar -xJf "$data" -C "$mod" "$member" 2>/dev/null ;;
    *.zst) tar --use-compress-program=unzstd -xf "$data" -C "$mod" "$member" 2>/dev/null ;;
    *.gz)  tar -xzf "$data" -C "$mod" "$member" 2>/dev/null ;;
    *)     echo "error: unsupported data tarball: $data" >&2; return 1 ;;
  esac
  local moddir="${mod}${member#.}"
  [[ -d "$moddir" ]] || { echo "error: 45drives-disks not found in $asset" >&2; return 1; }

  # Record the release tag for the parent shell (this function runs in a
  # command substitution, so plain variable assignments would not propagate).
  printf '%s' "${tag#v}" > "${WORK_DIR}/release-tag"
  printf '%s\n' "$moddir"
}

# --- Resolve a --source dir/tarball into a module directory ------------------
resolve_module_dir() {
  local src="$1" root
  if [[ -d "$src" ]]; then
    root="$src"
  elif [[ -f "$src" ]]; then
    root="${WORK_DIR}/extracted"; mkdir -p "$root"
    case "$src" in
      *.txz|*.tar.xz) tar -xJf "$src" -C "$root" ;;
      *.tgz|*.tar.gz) tar -xzf "$src" -C "$root" ;;
      *.tar)          tar -xf  "$src" -C "$root" ;;
      *) echo "error: unsupported source file type: $src" >&2; return 1 ;;
    esac
  else
    echo "error: source not found: $src" >&2; return 1
  fi

  is_module() { [[ -f "$1/index.html" ]] && compgen -G "$1/assets/index"* >/dev/null; }
  if is_module "$root"; then printf '%s\n' "$root"; return 0; fi
  local named
  named=$(find "$root" -type d -name 45drives-disks 2>/dev/null | head -n1 || true)
  if [[ -n "$named" ]] && is_module "$named"; then printf '%s\n' "$named"; return 0; fi
  local d
  while IFS= read -r d; do
    if is_module "$d"; then printf '%s\n' "$d"; return 0; fi
  done < <(find "$root" -type f -name index.html -exec dirname {} \; 2>/dev/null)
  echo "error: could not locate a 45drives-disks module (index.html + assets/) under $src" >&2
  return 1
}

if [[ -n "$RELEASE" ]]; then
  MODULE_DIR=$(fetch_release "$RELEASE")
  # Default the recorded version to the release tag when not given explicitly.
  if [[ -z "$VERSION" && -f "${WORK_DIR}/release-tag" ]]; then
    VERSION=$(cat "${WORK_DIR}/release-tag")
  fi
else
  MODULE_DIR=$(resolve_module_dir "$SOURCE")
fi
[[ -f "${MODULE_DIR}/index.html" ]] || { echo "error: resolved module has no index.html" >&2; exit 1; }
echo "Source module: ${MODULE_DIR}"

# Report the entry bundle change (handles both index.HASH.* and index-HASH.*).
entry_bundle() { grep -oE "assets/index[-.][A-Za-z0-9_]+\.$1" "$2" 2>/dev/null | head -n1 | sed 's#assets/##'; }
OLD_JS=$(entry_bundle js "${DEST_DIR}/index.html"); OLD_CSS=$(entry_bundle css "${DEST_DIR}/index.html")
NEW_JS=$(entry_bundle js "${MODULE_DIR}/index.html"); NEW_CSS=$(entry_bundle css "${MODULE_DIR}/index.html")
echo "  JS  bundle: ${OLD_JS:-<none>} -> ${NEW_JS:-<none>}"
echo "  CSS bundle: ${OLD_CSS:-<none>} -> ${NEW_CSS:-<none>}"

# Build the patched index.html: strip Cockpit-internal `src="../..."` scripts,
# inject the Unraid shim before </head>. Keeps upstream's own asset refs.
patch_index() {
  awk -v shimfile="$SHIM" '
    /<script[^>]*src="\.\.\// { next }
    /<\/head>/ { while ((getline l < shimfile) > 0) print l; close(shimfile); print; next }
    { print }
  ' "${MODULE_DIR}/index.html"
}

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo
  echo "Dry run -- would sync into ${DEST_DIR#${ROOT_DIR}/}/ :"
  rsync -ain --delete --exclude='index.html' "${MODULE_DIR}/" "${DEST_DIR}/" | sed 's/^/  /'
  echo
  echo "Would regenerate index.html (strip Cockpit-internal scripts, inject shim)."
  [[ -n "$VERSION" ]] && echo "Would record version ${VERSION#v} in ${ASSETS_README#${ROOT_DIR}/}."
  exit 0
fi

# Sync upstream module into place (drop stale hashed assets), then write our
# patched index.html over upstream's.
rsync -a --delete --exclude='index.html' "${MODULE_DIR}/" "${DEST_DIR}/"
patch_index > "${DEST_DIR}/index.html"

if [[ -n "$VERSION" ]]; then
  ver="${VERSION#v}"
  if grep -qE 'release snapshot \(v[^)]*\)' "$ASSETS_README"; then
    tmp=$(mktemp)
    sed -E "s/release snapshot \(v[^)]*\)/release snapshot (v${ver})/" "$ASSETS_README" > "$tmp"
    mv "$tmp" "$ASSETS_README"
    echo "Recorded version v${ver} in ${ASSETS_README#${ROOT_DIR}/}"
  else
    echo "warning: could not find the version line in ${ASSETS_README#${ROOT_DIR}/} to update" >&2
  fi
fi

echo
echo "Done. Review the diff, then QA on a real Unraid host:"
echo "  git status --short assets/45d/45drives-disks"
echo "  dev/live-deploy.sh --host root@<unraid-ip> --include-assets"
